{
 "title": "Atome History",
 "tags": [
  "atome",
  "history",
  "electricity",
  "power",
  "provisioned"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "atome" },
   {
    "name": "period",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"period\")"
   },
   { "name": "measurement_history", "query": "atome_history" },
   { "name": "datasource", "query": "influxdb" },
   { "name": "aggregation_createEmpty", "label": "Create empty", "query": "Yes : true, No : false" }
  ]
 },
 "panels": [
  {
   "title": "kWh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "lData=from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_history}\"\n            and\n                r.period =~ /^${period:regexp}+$/\n            and (\n                r._field    == \"totalConsumption\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \"::\" + r._field\n                    _field: \"Total\" // for \" + r.period\n                }\n            )\n        )\n    |>  yield(name: \"total\")\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_history}\"\n            and\n                r.period =~ /^${period:regexp}+$/\n            and (\n                r._field == \"consumption_HP_index\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \"::\" + r._field\n                    _field: \"HP\" // for \" + r.period\n                }\n            )\n        )\n    |>  yield(name: \"HP\")\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_history}\"\n            and\n                r.period =~ /^${period:regexp}+$/\n            and (\n                r._field ==\"consumption_HC_index\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \"::\" + r._field\n                    _field: \"HC\" // for \" + r.period\n                }\n            )\n        )\n    |>  yield(name: \"HC\")"
    }
   ]
  },
  {
   "title": "Bill",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_history}\"\n            and\n                r.period =~ /^${period:regexp}+$/\n            and\n                r._field =~ /^.*bill+.*/\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: sum,\n            createEmpty: ${aggregation_createEmpty}\n        )"
    }
   ]
  },
  {
   "title": "Price index",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_history}\"\n            and\n                r.period =~ /^${period:regexp}+$/\n            and\n                r._field =~ /^.*priceindex+.*/\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )"
    }
   ]
  }
 ]
}