{
 "title": "Atome Live",
 "tags": [
  "atome",
  "github.com/Aloike/python-gtw-atome-influxdb2",
  "live",
  "electricity",
  "power",
  "provisioned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "bucket", "query": "atome" },
   { "name": "measurement_live", "query": "atome_live" },
   { "name": "aggregation_createEmpty", "label": "Create empty", "query": "Yes : true, No : false" }
  ]
 },
 "panels": [
  {
   "title": "Connection state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    //|>  range(start: - 1m, stop:v.timeRangeStop)\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"isConnected\"\n            )\n        )\n\n    |>  last()\n\n//    |>  map(\n//            fn: (r) => (\n//                {\n//                    _value: r._value,\n//                    _time: r._time,\n//                    //_field: r.host + \" / \" + r._measurement + \"::\" + r._field\n//                    _field: r._measurement + \":: Last power\"\n//                }\n//            )\n        //)\n\n\n"
    }
   ]
  },
  {
   "title": "Connection state",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"isConnected\"\n            )\n        )\n\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: last,\n            createEmpty: ${aggregation_createEmpty}\n        )\n"
    }
   ]
  },
  {
   "title": "Subscribed power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"subscribed\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: false\n        )\n//    |>  last()\n\n"
    }
   ]
  },
  {
   "title": "Live power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"filteredPower\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \":: Filtered power\" + r._field\n                    //_field: \"Total for \" + r.period\n                    _field: r._measurement + \":: Filtered power\"\n                }\n            )\n        )\n    |>  yield(name: \"Filtered power\")\n\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"last\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \"::\" + r._field\n                    _field: r._measurement + \":: Last power\"\n                }\n            )\n        )\n    |>  yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Last power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            and (\n                r._field    == \"last\"\n            )\n        )\n        \n//    |>  map(\n//            fn: (r) => (\n//                {\n//                    _value: r._value,\n//                    _time: r._time,\n//                    //_field: r.host + \" / \" + r._measurement + \":: Filtered power\" + r._field\n//                    //_field: \"Total for \" + r.period\n//                }\n//            )\n//        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n    |>  yield(name: \"Filtered power\")\n"
    }
   ]
  },
  {
   "title": "Last W as % of subscribed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"last\"\n                or\n                r._field    == \"subscribed\"\n            )\n        )\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: false\n        )\n\n    // Align operand values into rows\n    |>  pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\n    // Calculate the percentage\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r.last * 100.0 / r.subscribed,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \":: Filtered power\" + r._field\n                    //_field: \"Total for \" + r.period\n                    _field: r._measurement + \":: Last power percentage\"\n                }\n            )\n        )\n\n"
    }
   ]
  },
  {
   "title": "Filtered power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            and (\n                r._field    == \"filteredPower\"\n            )\n        )\n\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: ${aggregation_createEmpty}\n        )\n\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r._value,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \":: Filtered power\" + r._field\n                    //_field: \"Total for \" + r.period\n                    _field: r._measurement + \":: Filtered power\"\n                }\n            )\n        )\n    |>  yield(name: \"Filtered power\")\n"
    }
   ]
  },
  {
   "title": "Filtered W as % of subscribed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |>  range(start: v.timeRangeStart, stop:v.timeRangeStop)\n    |>  filter(\n            fn: (r) =>\n                r._measurement == \"${measurement_live}\"\n            //and\n                //r.period =~ /^${period:json}+$/\n            and (\n                r._field    == \"filteredPower\"\n                or\n                r._field    == \"subscribed\"\n            )\n        )\n    |>  aggregateWindow(\n            every: v.windowPeriod,\n            fn: mean,\n            createEmpty: false\n        )\n\n    // Align operand values into rows\n    |>  pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\n    // Calculate the percentage\n    |>  map(\n            fn: (r) => (\n                {\n                    _value: r.filteredPower * 100.0 / r.subscribed,\n                    _time: r._time,\n                    //_field: r.host + \" / \" + r._measurement + \":: Filtered power\" + r._field\n                    //_field: \"Total for \" + r.period\n                    _field: r._measurement + \":: Filtered power percentage\"\n                }\n            )\n        )\n\n"
    }
   ]
  }
 ]
}